- hosts: workers
  become: yes
  vars_files:
    - vault.yaml 
  vars:
    ansible_become_pass: '{{ su_password }}'
  gather_facts: yes

  tasks:
  - name: disable swap
    shell: |
          sudo swapoff -a

  - name: reset kubeadmin
    shell: "kubeadm reset --force"
    ignore_errors: True

  - name: Copy join command from Ansiblehost to the worker nodes.
    become: yes
    copy:
      src: /tmp/kubernetes_join_command
      dest: /tmp/kubernetes_join_command
      mode: 0777

  - name: Join the Worker nodes to the cluster.
    become: yes
    command: sh /tmp/kubernetes_join_command
    register: joined_or_not
